# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information

app = "home-chatbot"
primary_region = "ams"  # Amsterdam - change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"
  PORT = "10000"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = false  # Important: keep bot running
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[mounts]
  source = "chatbot_data"
  destination = "/app/chroma_db"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
